export const cv = [
  {
    id: 1,
    title: "Ecole Nationale d'Informatique",
    subtitle: "Informatique Generale",
    date: "2020 - 2022",
    description: "qjjlqjljlqjljq",
    category: "Master",
  },

  {
    id: 2,
    title: "Developper Frontend$Backend",
    subtitle: "FERBER ENTERPRISES",
    date: "2020 - PRESENT",
    description: "qjjlqjljlqjljq",
    category: "Master",
  },
  {
    id: 3,
    title: "Developper Frontend$Backend",
    subtitle: "FERBER ENTERPRISES",
    date: "2020 - PRESENT",
    description: "qjjlqjljlqjljq",
    category: "Master",
  },
  {
    id: 4,
    title: "Developper Frontend$Backend",
    subtitle: "FERBER ENTERPRISES",
    date: "2020 - PRESENT",
    description: "qjjlqjljlqjljq",
    category: "experience",
  },
  {
    id: 5,
    title: "Developper Frontend$Backend",
    subtitle: "FERBER ENTERPRISES",
    date: "2020 - PRESENT",
    description: "qjjlqjljlqjljq",
    category: "experience",
  },
  {
    id: 6,
    title: "Developper Frontend$Backend",
    subtitle: "FERBER ENTERPRISES",
    date: "2020 - PRESENT",
    description: "qjjlqjljlqjljq",
    category: "experience",
  },
];
